# Generated by Django 5.2.5 on 2025-08-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Callection',
            new_name='Collection',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='callection',
            new_name='Collection',
        ),
    ]
