# Generated by Django 5.2.5 on 2025-08-27 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='feature_product',
            new_name='featured_product',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.order'),
        ),
    ]
