# Generated by Django 5.2.5 on 2025-08-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_callection_collection_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
                          INSERT INTO store_collection(title)
                          VALUES('collection1')
                          """, """
                          DELETE FROM store_collection
                          WHERE title = 'collection1'
                          """)
    ]
